build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [py-scrutinizer-run]
            
filter:
    excluded_paths:
        - tests/*