"""Source-backed flood-family identities and frozen public contracts (#1104).

These tests encode algebra printed in the primary sources and public signatures,
including the beta xarray dispatch, not vectors generated by climate_indices. Numeric
paper oracles remain unavailable; see ``tests/fixture/flood/README.md``. The
skip guards remain for a checkout without the flood package.
"""

from __future__ import annotations

import importlib
import inspect
from collections.abc import Callable
from types import ModuleType
from typing import Any

import numpy as np
import pytest

pytestmark = pytest.mark.validation


def _require_flood_module(issue: int) -> ModuleType:
    try:
        return importlib.import_module("climate_indices.flood")
    except ModuleNotFoundError as error:
        if error.name != "climate_indices.flood":
            raise
        pytest.skip(f"climate_indices.flood is not implemented; tracked by #{issue}")


def _require_flood_function(name: str, issue: int) -> Callable[..., Any]:
    function = getattr(_require_flood_module(issue), name, None)
    if function is None:
        pytest.skip(f"flood.{name}() is not implemented; tracked by #{issue}")
    return function


def test_flood_facade_omits_rejected_aliases() -> None:
    """Keep the ambiguous names rejected by ADR-0013 out of the public facade."""
    flood = _require_flood_module(1105)
    for name in ("api", "if_", "effective_drought_index"):
        assert not hasattr(flood, name)


@pytest.mark.parametrize(
    ("name", "issue", "expected"),
    [
        (
            "effective_precipitation",
            1105,
            (
                ("precipitation", inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.empty),
                ("duration", inspect.Parameter.KEYWORD_ONLY, 365),
                ("spatial_time_major", inspect.Parameter.KEYWORD_ONLY, False),
            ),
        ),
        (
            "edi",
            1106,
            (
                ("pe", inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.empty),
                ("data_start_year", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("calibration_year_initial", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("calibration_year_final", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("duration", inspect.Parameter.KEYWORD_ONLY, 365),
                ("spatial_time_major", inspect.Parameter.KEYWORD_ONLY, False),
            ),
        ),
        (
            "flood_index",
            1107,
            (
                ("pe", inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.empty),
                ("data_start_year", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("calibration_year_initial", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("calibration_year_final", inspect.Parameter.POSITIONAL_OR_KEYWORD, None),
                ("year_start_month", inspect.Parameter.KEYWORD_ONLY, inspect.Parameter.empty),
                ("spatial_time_major", inspect.Parameter.KEYWORD_ONLY, False),
            ),
        ),
        (
            "antecedent_precipitation_index",
            1109,
            (
                ("precipitation", inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.empty),
                ("k", inspect.Parameter.POSITIONAL_OR_KEYWORD, inspect.Parameter.empty),
                ("initial_state", inspect.Parameter.KEYWORD_ONLY, None),
                ("return_state", inspect.Parameter.KEYWORD_ONLY, False),
                ("spin_up", inspect.Parameter.KEYWORD_ONLY, 0),
                ("nan_policy", inspect.Parameter.KEYWORD_ONLY, "propagate"),
                ("max_gap_days", inspect.Parameter.KEYWORD_ONLY, 0),
                ("spatial_time_major", inspect.Parameter.KEYWORD_ONLY, False),
                ("time_dim", inspect.Parameter.KEYWORD_ONLY, "time"),
            ),
        ),
    ],
)
def test_planned_public_signature(name: str, issue: int, expected: tuple[tuple[str, Any, Any], ...]) -> None:
    """Freeze public names, argument kinds, and defaults for NumPy/xarray dispatch."""
    function = _require_flood_function(name, issue)
    actual = tuple(
        (parameter.name, parameter.kind, parameter.default)
        for parameter in inspect.signature(function).parameters.values()
    )
    assert actual == expected


@pytest.mark.parametrize(("name", "issue"), [("edi", 1106), ("flood_index", 1107)])
def test_numpy_flood_calibration_years_remain_required(name: str, issue: int) -> None:
    """Only labeled xarray inputs may infer calendar and Calibration Period years."""
    function = _require_flood_function(name, issue)
    kwargs = {"year_start_month": 1} if name == "flood_index" else {}
    with pytest.raises(TypeError, match="requires data_start_year and both calibration years"):
        function(np.ones(732), **kwargs)


def test_effective_precipitation_matches_equation_2_two_day_identity() -> None:
    """Byun and Wilhite Eq. (2): EP₂ = P₁ + (P₁ + P₂) / 2."""
    effective_precipitation = _require_flood_function("effective_precipitation", 1105)
    older, most_recent = 2.0, 4.0

    actual = effective_precipitation(np.array([older, most_recent]), duration=2)

    np.testing.assert_allclose(
        actual,
        [np.nan, most_recent + (most_recent + older) / 2],
        rtol=0.0,
        atol=0.0,
    )


def test_effective_precipitation_has_harmonic_endpoint_weights() -> None:
    """Eq. (2)'s newest and oldest weights are H_D and 1/D."""
    effective_precipitation = _require_flood_function("effective_precipitation", 1105)
    duration = 5
    newest_impulse = np.zeros(duration)
    newest_impulse[-1] = 1.0
    oldest_impulse = newest_impulse[::-1]

    newest_weight = effective_precipitation(newest_impulse, duration=duration)[-1]
    oldest_weight = effective_precipitation(oldest_impulse, duration=duration)[-1]

    assert newest_weight == pytest.approx(sum(1 / n for n in range(1, duration + 1)))
    assert oldest_weight == pytest.approx(1 / duration)


def test_antecedent_precipitation_converges_to_constant_input_closed_form() -> None:
    """Kohler and Linsley's non-lagged recurrence converges to P / (1 - k)."""
    antecedent_precipitation_index = _require_flood_function("antecedent_precipitation_index", 1109)
    precipitation = 2.0
    k = 0.5

    actual = antecedent_precipitation_index(np.full(60, precipitation), k)

    assert actual[-1] == pytest.approx(precipitation / (1 - k), rel=0.0, abs=1e-15)
