"""Regression tests for release-support scripts."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[1]


def _load_script(name: str, relative_path: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, ROOT / relative_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


create_github_issues = _load_script(
    "create_github_issues",
    "scripts/create_github_issues.py",
)
generate_llms_txt = _load_script(
    "generate_llms_txt",
    "scripts/generate_llms_txt.py",
)


def test_get_issue_labels_raises_on_gh_failure(monkeypatch: pytest.MonkeyPatch) -> None:
    """Issue label lookup should fail fast when gh cannot return labels."""

    def fail_run_gh(*_args: object, **_kwargs: object) -> str:
        raise subprocess.CalledProcessError(1, ["gh", "issue", "view"])

    monkeypatch.setattr(create_github_issues, "run_gh", fail_run_gh)

    with pytest.raises(RuntimeError, match="Failed to fetch labels for issue #42"):
        create_github_issues.get_issue_labels(42)


def test_get_issue_labels_raises_on_invalid_payload(monkeypatch: pytest.MonkeyPatch) -> None:
    """Issue label lookup should reject malformed gh JSON payloads."""
    monkeypatch.setattr(create_github_issues, "run_gh", lambda *_args, **_kwargs: "{}")

    with pytest.raises(RuntimeError, match="Invalid label payload for issue #42"):
        create_github_issues.get_issue_labels(42)


def test_get_labels_rejects_unknown_story_status() -> None:
    """Story status typos should not silently drop managed status labels."""
    story = {"slug": "e1-example", "status": "inprogress", "labels": ["epic:test"]}

    with pytest.raises(ValueError, match="inprogress.*e1-example"):
        create_github_issues.get_labels(story)


def test_read_missing_llms_source_names_file_and_source_lists() -> None:
    """Missing llms.txt source documents should report the bad path and lists."""
    missing_path = "docs/does-not-exist.md"

    with pytest.raises(FileNotFoundError) as exc_info:
        generate_llms_txt._read(missing_path)

    message = str(exc_info.value)
    assert missing_path in message
    assert "SUMMARY_FILES" in message
    assert "FULL_FILES" in message


@pytest.mark.parametrize(
    ("output", "sources"),
    [
        (Path("llms.txt"), generate_llms_txt.SUMMARY_FILES),
        (Path("llms-full.txt"), generate_llms_txt.FULL_FILES),
    ],
)
def test_llms_bundle_matches_configured_sources(output: Path, sources: list[str]) -> None:
    """Committed llms bundles should exactly match their configured sources."""
    assert (ROOT / output).read_text(encoding="utf-8") == generate_llms_txt._render(sources)


def test_render_builds_header_and_ordered_sections(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """_render should emit the fixed preamble followed by sections in source order."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)
    (tmp_path / "a.md").write_text("Content A\n", encoding="utf-8")
    (tmp_path / "b.md").write_text("Content B\n", encoding="utf-8")

    result = generate_llms_txt._render(["a.md", "b.md"])
    lines = result.splitlines()

    assert lines[0] == "# climate_indices"
    assert lines[1] == ""
    assert lines[2] == ("Reference implementations of climate and drought indices for scientific monitoring workflows.")
    assert lines[3] == ""
    assert lines[4] == "Generated by `uv run scripts/generate_llms_txt.py` from committed repository documentation."
    assert "## a.md\n\nContent A\n" in result
    assert "## b.md\n\nContent B\n" in result
    assert result.index("## a.md") < result.index("## b.md")


def test_render_strips_trailing_blank_lines_and_whitespace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """_render should end with exactly one trailing newline and no trailing whitespace."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)
    (tmp_path / "doc.md").write_text("Trailing space line.   \n\n\n", encoding="utf-8")

    result = generate_llms_txt._render(["doc.md"])

    assert "Trailing space line.   " not in result
    assert "Trailing space line." in result
    assert result.endswith("\n")
    assert not result.endswith("\n\n")


def test_render_preserves_internal_blank_lines_between_sections(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """_render must preserve blank lines inside a source file, not just strip trailing ones."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)
    (tmp_path / "doc.md").write_text("Para one.\n\nPara two.\n", encoding="utf-8")

    result = generate_llms_txt._render(["doc.md"])

    assert "## doc.md\n\nPara one.\n\nPara two.\n" in result


def test_render_repeats_section_for_duplicate_source_paths(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """_render must not deduplicate sources; each entry renders its own section."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)
    (tmp_path / "doc.md").write_text("Body.\n", encoding="utf-8")

    result = generate_llms_txt._render(["doc.md", "doc.md"])

    assert result.count("## doc.md") == 2


def test_render_with_no_sources_returns_only_preamble(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """An empty source list should still render the fixed preamble with no sections."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)

    result = generate_llms_txt._render([])

    assert "## " not in result
    assert result.startswith("# climate_indices")
    assert result.endswith("\n")
    assert not result.endswith("\n\n")


def test_render_propagates_missing_source_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """_render should surface the same FileNotFoundError raised by _read."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)

    with pytest.raises(FileNotFoundError, match="missing.md"):
        generate_llms_txt._render(["missing.md"])


def test_write_persists_render_output_to_disk(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """_write should write exactly what _render produces for the same sources."""
    monkeypatch.setattr(generate_llms_txt, "ROOT", tmp_path)
    (tmp_path / "doc.md").write_text("Hello, world.\n", encoding="utf-8")

    generate_llms_txt._write("out.txt", ["doc.md"])

    written = (tmp_path / "out.txt").read_text(encoding="utf-8")
    assert written == generate_llms_txt._render(["doc.md"])
