#!/usr/bin/env python3
"""Generate llms.txt and llms-full.txt from committed project docs."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SUMMARY_FILES = [
    "README.md",
    "VALIDATION.md",
    "docs/xarray_compatibility.md",
    "docs/algorithm_refs/eddi.md",
    "docs/algorithm_refs/palmer.md",
]

FULL_FILES = [
    *SUMMARY_FILES,
    "docs/project-overview.md",
    "docs/architecture.md",
    "docs/development-guide.md",
    "docs/contribution-guide.md",
    "docs/xarray_migration.rst",
    "docs/algorithms.rst",
]


def _read(path: str) -> str:
    """Read a UTF-8 documentation file relative to the repository root."""
    file_path = ROOT / path
    try:
        text = file_path.read_text(encoding="utf-8").strip()
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"Source document not found: {path}. Check SUMMARY_FILES and FULL_FILES in scripts/generate_llms_txt.py."
        ) from exc
    return "\n".join(line.rstrip() for line in text.splitlines())


def _section(path: str) -> str:
    """Render one source file as an llms.txt markdown section."""
    return f"## {path}\n\n{_read(path)}\n"


def _render(sources: list[str]) -> str:
    """Render an llms text bundle from the selected source files."""
    body = [
        "# climate_indices",
        "",
        "Reference implementations of climate and drought indices for scientific monitoring workflows.",
        "",
        "Generated by `uv run scripts/generate_llms_txt.py` from committed repository documentation.",
        "",
        *(_section(path) for path in sources),
    ]
    return "\n".join(body).rstrip() + "\n"


def _write(output: str, sources: list[str]) -> None:
    """Write an llms text file from the selected source files."""
    (ROOT / output).write_text(_render(sources), encoding="utf-8")


def main() -> None:
    """Generate both short and full AI-readable documentation bundles."""
    _write("llms.txt", SUMMARY_FILES)
    _write("llms-full.txt", FULL_FILES)


if __name__ == "__main__":
    main()
