#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import logging
import os
import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

# since our source files are under a src folder we need to add that as our first path
sys.path.insert(0, os.path.abspath("../src"))

# -- Project information -----------------------------------------------------

project = "climate_indices"
author = "James Adams"

# parse the version information from pyproject.toml
with open("../pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)

# get the full release version, including alpha/beta/rc tags
release = pyproject["project"]["version"]

# get the major.minor version
version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx_autodoc_typehints",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# RST and Markdown build side by side during the migration window. Every
# non-excluded Markdown page becomes a source document, so a published page
# joins the site by leaving `exclude_patterns` and entering a toctree, while
# internal pages stay in `exclude_patterns`.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# -- MyST configuration -------------------------------------------------------
# Heading anchors let a Markdown page cross-link to its own sections (the
# xarray compatibility matrix does, via `#chunking-guidance-...` links).
myst_heading_anchors = 3

# `colon_fence` is needed for `:::{warning}`-style Markdown admonitions,
# `dollarmath` for `$$ ... $$` display equations, and `deflist` for the
# definition lists the converted pages use.
myst_enable_extensions = ["colon_fence", "dollarmath", "deflist"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
# Internal working notes are excluded by path, not by convention: agent
# guidance, design/planning scratch, and research are addressed to
# maintainers and drift, so the site must never build them. Excluding them
# here also keeps them out of the Markdown build. See the
# "Documentation audience" section of CONTRIBUTING.md for the
# published/internal split and each published page's reader-need quadrant.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "agent/**",
    "design/**",
    "research/fire-indices-cli-approach.md",
    "research/interactive-climate-explorer-landscape.md",
    "research/dri-wrcc-scpdsi-assessment.md",
    "explorer/**",
    "architecture-deepening-review-*.md",
    "ai-assisted-development-report-*.md",
    "test_fixture_management.md",
    # Published Markdown pages not yet wired into navigation. Later tickets
    # publish them and delete their paths from this list: DOCS-7 (navigation)
    # and DOCS-8 (explanation and reference corpus).
    "ai-assisted-development.md",
    "algorithm_refs/**",
    "architecture.md",
    "contribution-guide.md",
    "deployment-guide.md",
    "development-guide.md",
    "floating_point_best_practices.md",
    "project-overview.md",
    "release-process.md",
    "research/nclimgrid-acquisition-and-redistribution.md",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Autodoc configuration ---------------------------------------------------
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
    "member-order": "bysource",
}
autodoc_typehints = "description"

# -- Napoleon configuration --------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_attr_annotations = True

# -- sphinx-autodoc-typehints ------------------------------------------------
typehints_fully_qualified = False
always_document_param_types = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# sphinx_rtd_theme defaults `includehidden` to True, which would put the
# staged-publication hidden toctree (the ADR build set in index.rst) into the
# sidebar. Keep hidden toctrees out of navigation.
html_theme_options = {"includehidden": False}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "climate_indicesdoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "climate_indices.tex",
        "climate\\_indices Documentation",
        author,
        "manual",
    )
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "climate_indices", "climate_indices Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "climate_indices",
        "climate_indices Documentation",
        "James Adams",
        "climate_indices",
        "Climate indices for drought monitoring",
        "Miscellaneous",
    )
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}


def _demote_intersphinx_outage(record: logging.LogRecord) -> bool:
    """Keep a transient external-inventory outage out of the warnings-as-errors gate.

    Intersphinx emits an untyped warning when no location for an inventory is
    reachable, and offers no configuration to demote it. Typed ``intersphinx``
    warnings (an unresolved reference) stay fatal, as does every warning from
    this project's own documentation.
    """
    if "intersphinx" in record.name and not getattr(record, "type", ""):
        record.levelno = logging.INFO
        record.levelname = "INFO"
    return True


# Sphinx's getLogger() prepends its namespace, and intersphinx passes in a
# name that already carries it, so cover both the doubled and the bare name.
for _logger_name in ("sphinx.ext.intersphinx", "sphinx.sphinx.ext.intersphinx"):
    logging.getLogger(_logger_name).addFilter(_demote_intersphinx_outage)

# -- Options for doctest extension -------------------------------------------
doctest_global_setup = """
import numpy as np
import pandas as pd
import xarray as xr
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
"""
